#!/bin/bash

DEP_FILE=requirements.txt
CMD=$1
DEP=$2

if [ -z $CMD ]
then
  printf "[dep] Please provide a dependency command (add,rm).\n"
  return -1
else
  if [ $CMD == "rm" ]
    if [ -z $DEP ]
    then
      printf "[dep] Please provide a dependency.\n"
      return -1
    else
      printf "[dep] Searching for dependency ...\n"
      LINE=`grep -F $DEP $DEP_FILE`

      if [ -z $LINE ]
      then
        printf "[dep] Dependency \"$DEP\" not found!\n"
        printf "[dep] Exiting ..."
        return -1
      else
        printf "[dep] Dependency \"$DEP\" found as \"$LINE\""
        printf "[dep] Removing dependency from $DEP_FILE ..."
        sed -i "/$DEP/d" $DEP_FILE
        printf "[dep] Sorting $DEP_FILE ...\n\n"
        sort $DEP_FILE -o $DEP_FILE
        cat $DEP_FILE
        printf "\n[dep] Dependency \"$LINE\" removed from $DEP_FILE.\n"
        printf "[dep] Done.\n"
        return 0
      fi
    fi
  then
  elif [ $CMD == "add" ]
    if [ -z $DEP ]
    then
      printf "[dep] Please provide a dependency.\n"
      printf "[dep] Exiting ...\n"
      return -1
    else
      printf "[dep] Searching for dependency ...\n"
      LINE=`pip3 freeze | grep -F $DEP`

      if [ -z $LINE ]
      then
        printf "[dep] Dependency \"$DEP\" not found!\n"
        printf "[dep] Exiting ...\n"
        return -1
      else
        printf "[dep] Dependency \"$DEP\" found as \"$LINE\"\n"
        printf "[dep] Adding dependency to $DEP_FILE (if absent) ...\n"
        grep -qxF $LINE $DEP_FILE || printf "$LINE\n" >> $DEP_FILE
        printf "[dep] Sorting $DEP_FILE ...\n\n"
        sort $DEP_FILE -o $DEP_FILE
        cat $DEP_FILE
        printf "\n[dep] Dependency \"$LINE\" added to $DEP_FILE.\n"
        printf "[dep] Done.\n"
        return 0
      fi
    fi
  else
    printf "[dep] Please provide a valid dependency command (add,rm).\n"
    return -1
  fi
fi

